language: java
script: mvn clean package
before_install:
 - openssl aes-256-cbc -K $encrypted_a94418be0ba2_key -iv $encrypted_a94418be0ba2_iv -in id_rsa.enc -out id_rsa -d
after_success: scripts/install_jar_in_repository.sh
