language: java

jdk: oraclejdk8
addons:
  apt:
    packages:
     - oracle-java8-installer

script: mvn clean package cobertura:cobertura

before_install: openssl aes-256-cbc -K $encrypted_a94418be0ba2_key -iv $encrypted_a94418be0ba2_iv -in id_rsa.enc -out id_rsa -d

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - scripts/install_jar_in_repository.sh
